# Permalinks
permalink:           pretty

# Setup
title:               HisAbimbola
tagline:             Personal Blog and portfolio
url:                 http://hisabimbola.com
shorturl:            hisabimbola.com

paginate:            1
baseurl:             ""

# Navbar
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Idowu Abimbola
  url:               https://twitter.com/hisabimbola
  email:             hisabimbola@gmail.com

# Enable comments
comments: true

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/hisabimbola/hisabimbola.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
